import { test, expect } from '@playwright/test';

test('real WebRTC: invitation, RTT, shared start, split controls, pause and disconnect', async ({ browser }) => {
  const first = await browser.newContext();
  const second = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true });
  const host = await first.newPage(), guest = await second.newPage();
  const errors = [];
  for (const page of [host, guest]) page.on('pageerror', (error) => errors.push(error.message));
  await host.goto('/#/multiplayer');
  await expect(host.locator('#invite-url')).toHaveValue(/room=/);
  const invite = await host.locator('#invite-url').inputValue();
  await guest.goto(invite);
  await expect(guest.locator('#connection-status')).toContainText('RTT', { timeout: 15000 });
  await expect(host.locator('#connection-status')).toContainText('RTT');
  await expect(host.locator('#coop-start')).toBeEnabled();
  await expect(guest.locator('#coop-start')).toBeHidden();
  const extra = await second.newPage();
  await extra.goto(invite);
  await expect(extra.locator('#connection-status')).toContainText('odpojil');
  await extra.close();
  await host.locator('#coop-start').click();
  await expect(guest.locator('#coop-status')).toContainText('Start za');
  await expect(host.locator('#coop-canvas')).toHaveAttribute('data-mode', 'running', { timeout: 6000 });
  await expect(guest.locator('#coop-canvas')).toHaveAttribute('data-mode', 'running');
  await host.keyboard.down('ArrowRight');
  await expect(host.locator('#right-indicator')).toContainText('puštěno');
  await host.keyboard.up('ArrowRight');
  await guest.keyboard.down('ArrowLeft');
  await expect(guest.locator('#left-indicator')).toContainText('puštěno');
  await guest.keyboard.up('ArrowLeft');
  await host.keyboard.down('ArrowLeft');
  await expect(guest.locator('#left-indicator')).toContainText('stisknuto');
  await host.keyboard.up('ArrowLeft');
  await expect(guest.locator('#left-indicator')).toContainText('puštěno');
  const control = await guest.locator('#coop-turn').boundingBox();
  await guest.mouse.move(control.x + control.width / 2, control.y + control.height / 2);
  await guest.mouse.down();
  await expect(host.locator('#right-indicator')).toContainText('stisknuto');
  await guest.mouse.up();
  await expect(host.locator('#right-indicator')).toContainText('puštěno');
  await guest.evaluate(() => {
    Object.defineProperty(document, 'hidden', { configurable: true, value: true });
    document.dispatchEvent(new Event('visibilitychange'));
  });
  await expect(host.locator('#coop-status')).toContainText('Čekáme');
  const tick = await host.locator('#coop-canvas').getAttribute('data-tick');
  await expect(guest.locator('#coop-canvas')).toHaveAttribute('data-tick', tick);
  expect(await guest.locator('#coop-canvas').evaluate((canvas) => canvas.toDataURL())).toBe(
    await host.locator('#coop-canvas').evaluate((canvas) => canvas.toDataURL()));
  await guest.screenshot({ path: 'test-results/coop-mobile.png', fullPage: true });
  await guest.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, value: false }); });
  await host.locator('#coop-start').click();
  await expect(guest.locator('#coop-status')).toContainText('Společná jízda', { timeout: 6000 });
  expect(await guest.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await guest.close();
  await expect(host.locator('#connection-status')).toContainText(/odpojil|přerušilo/, { timeout: 15000 });
  await expect(host.locator('#coop-turn')).toBeDisabled();
  await host.locator('#coop-new').click();
  await expect(host.locator('#invite-url')).toHaveValue(/room=/);
  expect(await host.locator('#invite-url').inputValue()).not.toBe(invite);
  expect(errors).toEqual([]);
  await first.close(); await second.close();
});
